CREATE TABLE "project" (
	"project_id" SERIAL NOT NULL UNIQUE,
	"project_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("project_id")
);




CREATE TABLE "units_type" (
	"unit_type_id" SERIAL NOT NULL UNIQUE,
	"unit_type_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("unit_type_id")
);




CREATE TABLE "units" (
	"unit_id" SERIAL NOT NULL UNIQUE,
	"unit_type_id" INTEGER NOT NULL,
	"unit_name" VARCHAR(255),
	PRIMARY KEY("unit_id")
);




CREATE TABLE "positions" (
	"position_id" SERIAL NOT NULL UNIQUE,
	"position_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("position_id")
);




CREATE TABLE "branches" (
	"branch_id" SERIAL NOT NULL UNIQUE,
	"branch_address" TEXT NOT NULL,
	PRIMARY KEY("branch_id")
);




CREATE TABLE "employees" (
	"emp_id" SERIAL NOT NULL UNIQUE,
	"emp_last_name" VARCHAR(255) NOT NULL,
	"emp_first_name" VARCHAR(255) NOT NULL,
	"emp_patronymic" VARCHAR(255) NOT NULL,
	"position_id" INTEGER NOT NULL,
	"unit_id" INTEGER NOT NULL,
	"emp_date_employment" DATE NOT NULL,
	"branch_id" INTEGER NOT NULL,
	PRIMARY KEY("emp_id")
);




CREATE TABLE "project_employee" (
	"emp_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"project_id" INTEGER NOT NULL,
	PRIMARY KEY("emp_id", "project_id")
);



ALTER TABLE "units"
ADD FOREIGN KEY("unit_type_id") REFERENCES "units_type"("unit_type_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "employees"
ADD FOREIGN KEY("position_id") REFERENCES "positions"("position_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "employees"
ADD FOREIGN KEY("unit_id") REFERENCES "units"("unit_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "employees"
ADD FOREIGN KEY("branch_id") REFERENCES "branches"("branch_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "project_employee"
ADD FOREIGN KEY("emp_id") REFERENCES "employees"("emp_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "project_employee"
ADD FOREIGN KEY("project_id") REFERENCES "project"("project_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;